services:
  localdb:
    container_name: kniitter
    image: mysql:8.0
    ports:
      - 3312:3306
    expose:
      - 3312
    environment:
      MYSQL_ROOT_PASSWORD: My@Kniit
      MYSQL_DATABASE: knitdb
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
      - --log_bin_trust_function_creators=1
      - --default-time-zone=Asia/Seoul

    volumes:
      # - ./mysql:/var/lib/mysql
      - mysql-data:/var/lib/mysql

volumes:
  mysql-data:
