services:
  localdb:
    container_name: kniitter
    image: postgres:16-alpine
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: My@Kniit
      POSTGRES_DB: knitdb
      TZ: Asia/Seoul

    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:
